repos:
  # Ruff - linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  # Poetry - dependency management
  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.0'  # add version here
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
